/* data.js — the objects on record. GENERATED by gen_catalog.py — do not hand-edit.
   the standard pack · case — 002 · unit no. 04-2891.
   prices + variant ids mirror the shopify store (iesefi-cx.myshopify.com).
   images served from the shopify cdn, width-capped, rendered b&w by css. */

window.VRSN_STORE = 'https://iesefi-cx.myshopify.com';

window.VRSN_PRODUCTS = [
  {
    "id": "the-standard-issue",
    "name": "the standard issue",
    "observed": "required equipment",
    "sub": "case — 002 · the standard pack",
    "type": "hazmat suit",
    "price": 333.0,
    "handle": "hazmat-suit",
    "categories": [
      "men",
      "women"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039026_0_3d.jpg?v=1783804262",
    "options": [
      {
        "label": "select size",
        "values": [
          "s",
          "m",
          "l",
          "xl"
        ]
      },
      {
        "label": "select cord",
        "values": [
          "white",
          "black",
          "orange",
          "pink",
          "green"
        ]
      }
    ],
    "variants": {
      "s|white": {
        "vid": 50397275816129
      },
      "s|black": {
        "vid": 50397275848897
      },
      "s|orange": {
        "vid": 50397275881665
      },
      "s|pink": {
        "vid": 50397275914433
      },
      "s|green": {
        "vid": 50397275947201
      },
      "m|white": {
        "vid": 50397275979969
      },
      "m|black": {
        "vid": 50397276012737
      },
      "m|orange": {
        "vid": 50397276045505
      },
      "m|pink": {
        "vid": 50397276078273
      },
      "m|green": {
        "vid": 50397276111041
      },
      "l|white": {
        "vid": 50397276143809
      },
      "l|black": {
        "vid": 50397276176577
      },
      "l|orange": {
        "vid": 50397276209345
      },
      "l|pink": {
        "vid": 50397276242113
      },
      "l|green": {
        "vid": 50397276274881
      },
      "xl|white": {
        "vid": 50397276307649
      },
      "xl|black": {
        "vid": 50397276340417
      },
      "xl|orange": {
        "vid": 50397276373185
      },
      "xl|pink": {
        "vid": 50397276405953
      },
      "xl|green": {
        "vid": 50397276438721
      }
    },
    "desc": "issued.\n\nhazmat suit. poly waterproof fabric. zip-up front. hooded. handmade to order.\n\nchest stamp: commission for uniform provision · standard issue — tier 2 · cycle 04.\nback: barcode. unit no. 04-2891.\n\nyou are not a person wearing clothes. you are a unit carrying its current cycle's issue.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-poncho",
    "name": "the poncho",
    "observed": "scheduled precipitation",
    "sub": "case — 002 · the standard pack",
    "type": "rain poncho",
    "price": 283.0,
    "handle": "pullover-rain-poncho",
    "categories": [
      "men",
      "women"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039022_0_3d.jpg?v=1783804244",
    "options": [
      {
        "label": "select cord",
        "values": [
          "white",
          "black",
          "orange",
          "pink",
          "green"
        ]
      },
      {
        "label": "select pocket",
        "values": [
          "no pocket",
          "with pocket"
        ]
      },
      {
        "label": "select hardware",
        "values": [
          "silver",
          "graphite"
        ]
      }
    ],
    "variants": {
      "white|no pocket|silver": {
        "vid": 50397275095233
      },
      "white|no pocket|graphite": {
        "vid": 50397275128001
      },
      "white|with pocket|silver": {
        "vid": 50397275160769
      },
      "white|with pocket|graphite": {
        "vid": 50397275193537
      },
      "black|no pocket|silver": {
        "vid": 50397275226305
      },
      "black|no pocket|graphite": {
        "vid": 50397275259073
      },
      "black|with pocket|silver": {
        "vid": 50397275291841
      },
      "black|with pocket|graphite": {
        "vid": 50397275324609
      },
      "orange|no pocket|silver": {
        "vid": 50397275357377
      },
      "orange|no pocket|graphite": {
        "vid": 50397275390145
      },
      "orange|with pocket|silver": {
        "vid": 50397275422913
      },
      "orange|with pocket|graphite": {
        "vid": 50397275455681
      },
      "pink|no pocket|silver": {
        "vid": 50397275488449
      },
      "pink|no pocket|graphite": {
        "vid": 50397275521217
      },
      "pink|with pocket|silver": {
        "vid": 50397275553985
      },
      "pink|with pocket|graphite": {
        "vid": 50397275586753
      },
      "green|no pocket|silver": {
        "vid": 50397275619521
      },
      "green|no pocket|graphite": {
        "vid": 50397275652289
      },
      "green|with pocket|silver": {
        "vid": 50397275685057
      },
      "green|with pocket|graphite": {
        "vid": 50397275717825
      }
    },
    "desc": "issued.\n\npullover rain poncho. waterproof. hooded. handmade to order.\n\nchest stamp: commission for uniform provision · standard issue — tier 2 · cycle 07.\nback: barcode. unit no. 04-2891.\n\nprecipitation is scheduled. so is your protection from it.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-roll-neck",
    "name": "the roll neck",
    "observed": "a managed input",
    "sub": "case — 002 · the standard pack",
    "type": "base layer top",
    "price": 113.0,
    "handle": "mens-slim-fit-roll-neck",
    "categories": [
      "men",
      "women"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039036_0_3d.jpg?v=1783825131",
    "options": [
      {
        "label": "select size",
        "values": [
          "2xs",
          "xs",
          "s",
          "m",
          "l",
          "xl",
          "2xl"
        ]
      },
      {
        "label": "select fabric",
        "values": [
          "recycled jersey",
          "silky jersey"
        ]
      }
    ],
    "variants": {
      "2xs|recycled jersey": {
        "vid": 50397525180609
      },
      "2xs|silky jersey": {
        "vid": 50397525213377
      },
      "xs|recycled jersey": {
        "vid": 50397525246145
      },
      "xs|silky jersey": {
        "vid": 50397525278913
      },
      "s|recycled jersey": {
        "vid": 50397525311681
      },
      "s|silky jersey": {
        "vid": 50397525344449
      },
      "m|recycled jersey": {
        "vid": 50397525377217
      },
      "m|silky jersey": {
        "vid": 50397525409985
      },
      "l|recycled jersey": {
        "vid": 50397525442753
      },
      "l|silky jersey": {
        "vid": 50397525475521
      },
      "xl|recycled jersey": {
        "vid": 50397525508289
      },
      "xl|silky jersey": {
        "vid": 50397525541057
      },
      "2xl|recycled jersey": {
        "vid": 50397525573825
      },
      "2xl|silky jersey": {
        "vid": 50397525606593
      }
    },
    "desc": "issued.\n\nbase layer, slim fit roll neck. recycled polyester jersey, 200gsm, black trim. handmade to order.\n\nchest stamp: commission for uniform provision · standard issue — tier 2 · cycle 04.\nback: barcode. unit no. 04-2891.\n\nrecycled material. the commission manages its inputs. you are one of them.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-trousers",
    "name": "the trousers",
    "observed": "the lower allotment",
    "sub": "case — 002 · the standard pack",
    "type": "base layer bottom",
    "price": 93.0,
    "handle": "mens-pyjama-bottoms",
    "categories": [
      "men",
      "women"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039498_0_3d.jpg?v=1783803969",
    "options": [
      {
        "label": "select size",
        "values": [
          "xs",
          "s",
          "m",
          "l",
          "xl",
          "2xl",
          "3xl",
          "4xl",
          "5xl",
          "6xl",
          "7xl"
        ]
      },
      {
        "label": "select fabric",
        "values": [
          "jersey",
          "organic cotton"
        ]
      }
    ],
    "variants": {
      "xs|jersey": {
        "vid": 50397267820737
      },
      "xs|organic cotton": {
        "vid": 50397267853505,
        "price": 123.0
      },
      "s|jersey": {
        "vid": 50397267886273
      },
      "s|organic cotton": {
        "vid": 50397267919041,
        "price": 123.0
      },
      "m|jersey": {
        "vid": 50397267951809
      },
      "m|organic cotton": {
        "vid": 50397267984577,
        "price": 123.0
      },
      "l|jersey": {
        "vid": 50397268017345
      },
      "l|organic cotton": {
        "vid": 50397268050113,
        "price": 123.0
      },
      "xl|jersey": {
        "vid": 50397268082881
      },
      "xl|organic cotton": {
        "vid": 50397268115649,
        "price": 123.0
      },
      "2xl|jersey": {
        "vid": 50397268148417
      },
      "2xl|organic cotton": {
        "vid": 50397268181185,
        "price": 123.0
      },
      "3xl|jersey": {
        "vid": 50397268213953
      },
      "3xl|organic cotton": {
        "vid": 50397268246721,
        "price": 123.0
      },
      "4xl|jersey": {
        "vid": 50397268279489
      },
      "4xl|organic cotton": {
        "vid": 50397268312257,
        "price": 123.0
      },
      "5xl|jersey": {
        "vid": 50397268345025
      },
      "5xl|organic cotton": {
        "vid": 50397268377793,
        "price": 123.0
      },
      "6xl|jersey": {
        "vid": 50397268410561
      },
      "6xl|organic cotton": {
        "vid": 50397268443329,
        "price": 123.0
      },
      "7xl|jersey": {
        "vid": 50397268476097
      },
      "7xl|organic cotton": {
        "vid": 50397268508865,
        "price": 123.0
      }
    },
    "desc": "issued.\n\nbase layer bottom. elastic waistband, side pockets, loose fit. handmade to order.\n\npairs with the roll neck. a unit's base layer is issued as a set.\n\nchest stamp: commission for uniform provision · standard issue — tier 2 · cycle 04.\nunit no. 04-2891.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-tee",
    "name": "the tee",
    "observed": "cycle 04",
    "sub": "case — 002 · the standard pack",
    "type": "oversized tee",
    "price": 123.0,
    "handle": "mens-oversized-t-shirt",
    "categories": [
      "men",
      "women"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039042_0_3d.jpg?v=1783806188",
    "options": [
      {
        "label": "select size",
        "values": [
          "xs",
          "s",
          "m",
          "l",
          "xl",
          "2xl",
          "3xl",
          "4xl",
          "5xl",
          "6xl",
          "7xl"
        ]
      },
      {
        "label": "select fabric",
        "values": [
          "ponte jersey",
          "bounce cotton"
        ]
      }
    ],
    "variants": {
      "xs|ponte jersey": {
        "vid": 50397284597953
      },
      "xs|bounce cotton": {
        "vid": 50397284630721,
        "price": 163.0
      },
      "s|ponte jersey": {
        "vid": 50397284663489
      },
      "s|bounce cotton": {
        "vid": 50397284696257,
        "price": 163.0
      },
      "m|ponte jersey": {
        "vid": 50397284729025
      },
      "m|bounce cotton": {
        "vid": 50397284761793,
        "price": 163.0
      },
      "l|ponte jersey": {
        "vid": 50397284794561
      },
      "l|bounce cotton": {
        "vid": 50397284827329,
        "price": 163.0
      },
      "xl|ponte jersey": {
        "vid": 50397284860097
      },
      "xl|bounce cotton": {
        "vid": 50397284892865,
        "price": 163.0
      },
      "2xl|ponte jersey": {
        "vid": 50397284925633
      },
      "2xl|bounce cotton": {
        "vid": 50397284958401,
        "price": 163.0
      },
      "3xl|ponte jersey": {
        "vid": 50397284991169
      },
      "3xl|bounce cotton": {
        "vid": 50397285023937,
        "price": 163.0
      },
      "4xl|ponte jersey": {
        "vid": 50397285056705
      },
      "4xl|bounce cotton": {
        "vid": 50397285089473,
        "price": 163.0
      },
      "5xl|ponte jersey": {
        "vid": 50397285122241
      },
      "5xl|bounce cotton": {
        "vid": 50397285155009,
        "price": 163.0
      },
      "6xl|ponte jersey": {
        "vid": 50397285187777
      },
      "6xl|bounce cotton": {
        "vid": 50397285220545,
        "price": 163.0
      },
      "7xl|ponte jersey": {
        "vid": 50397285253313
      },
      "7xl|bounce cotton": {
        "vid": 50397285286081,
        "price": 163.0
      }
    },
    "desc": "issued.\n\noversized boxy tee. heavyweight jersey. handmade to order.\n\nchest stamp: commission for uniform provision · standard issue — tier 2 · cycle 04.\nback: barcode, high and centered below the collar seam. unit no. 04-2891.\n\nequity of appearance: nobody over, nobody under, nobody anybody.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-tag",
    "name": "the tag",
    "observed": "you, in ledger form",
    "sub": "case — 002 · the standard pack",
    "type": "unit identifier",
    "price": 123.0,
    "handle": "leather-keyring",
    "categories": [
      "accessories"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039051_0_3d.jpg?v=1783804523",
    "options": [
      {
        "label": "select shape",
        "values": [
          "rectangle",
          "heart"
        ]
      },
      {
        "label": "select leather",
        "values": [
          "smooth nappa",
          "textured nappa"
        ]
      },
      {
        "label": "select edge",
        "values": [
          "black thread",
          "charcoal",
          "cream",
          "red",
          "blue",
          "brown"
        ]
      }
    ],
    "variants": {
      "rectangle|smooth nappa|black thread": {
        "vid": 50397278109889
      },
      "rectangle|smooth nappa|charcoal": {
        "vid": 50397278142657
      },
      "rectangle|smooth nappa|cream": {
        "vid": 50397278175425
      },
      "rectangle|smooth nappa|red": {
        "vid": 50397278208193
      },
      "rectangle|smooth nappa|blue": {
        "vid": 50397278240961
      },
      "rectangle|smooth nappa|brown": {
        "vid": 50397278273729
      },
      "rectangle|textured nappa|black thread": {
        "vid": 50397278306497
      },
      "rectangle|textured nappa|charcoal": {
        "vid": 50397278339265
      },
      "rectangle|textured nappa|cream": {
        "vid": 50397278372033
      },
      "rectangle|textured nappa|red": {
        "vid": 50397278404801
      },
      "rectangle|textured nappa|blue": {
        "vid": 50397278437569
      },
      "rectangle|textured nappa|brown": {
        "vid": 50397278470337
      },
      "heart|smooth nappa|black thread": {
        "vid": 50397278503105
      },
      "heart|smooth nappa|charcoal": {
        "vid": 50397278535873
      },
      "heart|smooth nappa|cream": {
        "vid": 50397278568641
      },
      "heart|smooth nappa|red": {
        "vid": 50397278601409
      },
      "heart|smooth nappa|blue": {
        "vid": 50397278634177
      },
      "heart|smooth nappa|brown": {
        "vid": 50397278666945
      },
      "heart|textured nappa|black thread": {
        "vid": 50397278699713
      },
      "heart|textured nappa|charcoal": {
        "vid": 50397278732481
      },
      "heart|textured nappa|cream": {
        "vid": 50397278765249
      },
      "heart|textured nappa|red": {
        "vid": 50397278798017
      },
      "heart|textured nappa|blue": {
        "vid": 50397278830785
      },
      "heart|textured nappa|brown": {
        "vid": 50397278863553
      }
    },
    "desc": "issued.\n\nunit identifier. printed, padded leather. double sided. silver ring. handmade to order.\n\nfront: barcode. unit no. 04-2891.\nback: commission for uniform provision · standard issue — tier 2 · cycle 04.\n\nthe garments are what the allotment entitles you to. this is the allotment. carry it.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-fanny-pack",
    "name": "the fanny pack",
    "observed": "carried weight",
    "sub": "case — 002 · the standard pack",
    "type": "carry unit",
    "price": 343.0,
    "handle": "fanny-pack",
    "categories": [
      "accessories"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039048_0_3d.jpg?v=1783804707",
    "options": [
      {
        "label": "select strap",
        "values": [
          "standard · waist",
          "long · cross body"
        ]
      },
      {
        "label": "select material",
        "values": [
          "nappa leather",
          "brushed twill"
        ]
      }
    ],
    "variants": {
      "standard · waist|nappa leather": {
        "vid": 50397284466881
      },
      "standard · waist|brushed twill": {
        "vid": 50397284499649
      },
      "long · cross body|nappa leather": {
        "vid": 50397284532417
      },
      "long · cross body|brushed twill": {
        "vid": 50397284565185
      }
    },
    "desc": "issued.\n\ncarry unit. 100% nappa leather, handmade to order. adjustable strap.\n\nstamp, small scale, beside the zipper: commission for uniform provision · standard issue — tier 2 · cycle 04.\n\ncontents are the unit's own. this is noted, not encouraged.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-vest",
    "name": "the vest",
    "observed": "black issue",
    "sub": "case — 002 · the standard pack",
    "type": "puffer vest",
    "price": 833.0,
    "handle": "unisex-gilet",
    "categories": [
      "men",
      "women"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039057_0_3d.jpg?v=1783804553",
    "options": [
      {
        "label": "select size",
        "values": [
          "xs",
          "s",
          "m",
          "l",
          "xl",
          "2xl",
          "3xl",
          "4xl"
        ]
      },
      {
        "label": "select fabric",
        "values": [
          "splash proof",
          "silk satin"
        ]
      },
      {
        "label": "select zip",
        "values": [
          "white",
          "black",
          "cream",
          "red",
          "green",
          "blue",
          "yellow",
          "pink"
        ]
      }
    ],
    "variants": {
      "xs|splash proof|white": {
        "vid": 50397279125697
      },
      "xs|splash proof|black": {
        "vid": 50397279158465
      },
      "xs|splash proof|cream": {
        "vid": 50397279191233
      },
      "xs|splash proof|red": {
        "vid": 50397279224001
      },
      "xs|splash proof|green": {
        "vid": 50397279256769
      },
      "xs|splash proof|blue": {
        "vid": 50397279289537
      },
      "xs|splash proof|yellow": {
        "vid": 50397279322305
      },
      "xs|splash proof|pink": {
        "vid": 50397279355073
      },
      "xs|silk satin|white": {
        "vid": 50397279387841,
        "price": 1033.0
      },
      "xs|silk satin|black": {
        "vid": 50397279420609,
        "price": 1033.0
      },
      "xs|silk satin|cream": {
        "vid": 50397279453377,
        "price": 1033.0
      },
      "xs|silk satin|red": {
        "vid": 50397279486145,
        "price": 1033.0
      },
      "xs|silk satin|green": {
        "vid": 50397279518913,
        "price": 1033.0
      },
      "xs|silk satin|blue": {
        "vid": 50397279551681,
        "price": 1033.0
      },
      "xs|silk satin|yellow": {
        "vid": 50397279584449,
        "price": 1033.0
      },
      "xs|silk satin|pink": {
        "vid": 50397279617217,
        "price": 1033.0
      },
      "s|splash proof|white": {
        "vid": 50397279649985
      },
      "s|splash proof|black": {
        "vid": 50397279682753
      },
      "s|splash proof|cream": {
        "vid": 50397279715521
      },
      "s|splash proof|red": {
        "vid": 50397279748289
      },
      "s|splash proof|green": {
        "vid": 50397279781057
      },
      "s|splash proof|blue": {
        "vid": 50397279813825
      },
      "s|splash proof|yellow": {
        "vid": 50397279846593
      },
      "s|splash proof|pink": {
        "vid": 50397279879361
      },
      "s|silk satin|white": {
        "vid": 50397279912129,
        "price": 1033.0
      },
      "s|silk satin|black": {
        "vid": 50397279944897,
        "price": 1033.0
      },
      "s|silk satin|cream": {
        "vid": 50397279977665,
        "price": 1033.0
      },
      "s|silk satin|red": {
        "vid": 50397280010433,
        "price": 1033.0
      },
      "s|silk satin|green": {
        "vid": 50397280043201,
        "price": 1033.0
      },
      "s|silk satin|blue": {
        "vid": 50397280075969,
        "price": 1033.0
      },
      "s|silk satin|yellow": {
        "vid": 50397280108737,
        "price": 1033.0
      },
      "s|silk satin|pink": {
        "vid": 50397280141505,
        "price": 1033.0
      },
      "m|splash proof|white": {
        "vid": 50397280174273
      },
      "m|splash proof|black": {
        "vid": 50397280207041
      },
      "m|splash proof|cream": {
        "vid": 50397280239809
      },
      "m|splash proof|red": {
        "vid": 50397280272577
      },
      "m|splash proof|green": {
        "vid": 50397280305345
      },
      "m|splash proof|blue": {
        "vid": 50397280338113
      },
      "m|splash proof|yellow": {
        "vid": 50397280370881
      },
      "m|splash proof|pink": {
        "vid": 50397280403649
      },
      "m|silk satin|white": {
        "vid": 50397280436417,
        "price": 1033.0
      },
      "m|silk satin|black": {
        "vid": 50397280469185,
        "price": 1033.0
      },
      "m|silk satin|cream": {
        "vid": 50397280501953,
        "price": 1033.0
      },
      "m|silk satin|red": {
        "vid": 50397280534721,
        "price": 1033.0
      },
      "m|silk satin|green": {
        "vid": 50397280567489,
        "price": 1033.0
      },
      "m|silk satin|blue": {
        "vid": 50397280600257,
        "price": 1033.0
      },
      "m|silk satin|yellow": {
        "vid": 50397280633025,
        "price": 1033.0
      },
      "m|silk satin|pink": {
        "vid": 50397280665793,
        "price": 1033.0
      },
      "l|splash proof|white": {
        "vid": 50397280698561
      },
      "l|splash proof|black": {
        "vid": 50397280731329
      },
      "l|splash proof|cream": {
        "vid": 50397280764097
      },
      "l|splash proof|red": {
        "vid": 50397280796865
      },
      "l|splash proof|green": {
        "vid": 50397280829633
      },
      "l|splash proof|blue": {
        "vid": 50397280862401
      },
      "l|splash proof|yellow": {
        "vid": 50397280895169
      },
      "l|splash proof|pink": {
        "vid": 50397280927937
      },
      "l|silk satin|white": {
        "vid": 50397280960705,
        "price": 1033.0
      },
      "l|silk satin|black": {
        "vid": 50397280993473,
        "price": 1033.0
      },
      "l|silk satin|cream": {
        "vid": 50397281026241,
        "price": 1033.0
      },
      "l|silk satin|red": {
        "vid": 50397281059009,
        "price": 1033.0
      },
      "l|silk satin|green": {
        "vid": 50397281091777,
        "price": 1033.0
      },
      "l|silk satin|blue": {
        "vid": 50397281124545,
        "price": 1033.0
      },
      "l|silk satin|yellow": {
        "vid": 50397281157313,
        "price": 1033.0
      },
      "l|silk satin|pink": {
        "vid": 50397281190081,
        "price": 1033.0
      },
      "xl|splash proof|white": {
        "vid": 50397281222849
      },
      "xl|splash proof|black": {
        "vid": 50397281255617
      },
      "xl|splash proof|cream": {
        "vid": 50397281288385
      },
      "xl|splash proof|red": {
        "vid": 50397281321153
      },
      "xl|splash proof|green": {
        "vid": 50397281353921
      },
      "xl|splash proof|blue": {
        "vid": 50397281386689
      },
      "xl|splash proof|yellow": {
        "vid": 50397281419457
      },
      "xl|splash proof|pink": {
        "vid": 50397281452225
      },
      "xl|silk satin|white": {
        "vid": 50397281484993,
        "price": 1033.0
      },
      "xl|silk satin|black": {
        "vid": 50397281517761,
        "price": 1033.0
      },
      "xl|silk satin|cream": {
        "vid": 50397281550529,
        "price": 1033.0
      },
      "xl|silk satin|red": {
        "vid": 50397281583297,
        "price": 1033.0
      },
      "xl|silk satin|green": {
        "vid": 50397281616065,
        "price": 1033.0
      },
      "xl|silk satin|blue": {
        "vid": 50397281648833,
        "price": 1033.0
      },
      "xl|silk satin|yellow": {
        "vid": 50397281681601,
        "price": 1033.0
      },
      "xl|silk satin|pink": {
        "vid": 50397281714369,
        "price": 1033.0
      },
      "2xl|splash proof|white": {
        "vid": 50397281747137
      },
      "2xl|splash proof|black": {
        "vid": 50397281779905
      },
      "2xl|splash proof|cream": {
        "vid": 50397281812673
      },
      "2xl|splash proof|red": {
        "vid": 50397281845441
      },
      "2xl|splash proof|green": {
        "vid": 50397281878209
      },
      "2xl|splash proof|blue": {
        "vid": 50397281910977
      },
      "2xl|splash proof|yellow": {
        "vid": 50397281943745
      },
      "2xl|splash proof|pink": {
        "vid": 50397281976513
      },
      "2xl|silk satin|white": {
        "vid": 50397282009281,
        "price": 1033.0
      },
      "2xl|silk satin|black": {
        "vid": 50397282042049,
        "price": 1033.0
      },
      "2xl|silk satin|cream": {
        "vid": 50397282074817,
        "price": 1033.0
      },
      "2xl|silk satin|red": {
        "vid": 50397282107585,
        "price": 1033.0
      },
      "2xl|silk satin|green": {
        "vid": 50397282140353,
        "price": 1033.0
      },
      "2xl|silk satin|blue": {
        "vid": 50397282173121,
        "price": 1033.0
      },
      "2xl|silk satin|yellow": {
        "vid": 50397282205889,
        "price": 1033.0
      },
      "2xl|silk satin|pink": {
        "vid": 50397282238657,
        "price": 1033.0
      },
      "3xl|splash proof|white": {
        "vid": 50397282271425
      },
      "3xl|splash proof|black": {
        "vid": 50397282304193
      },
      "3xl|splash proof|cream": {
        "vid": 50397282336961
      },
      "3xl|splash proof|red": {
        "vid": 50397282369729
      },
      "3xl|splash proof|green": {
        "vid": 50397282402497
      },
      "3xl|splash proof|blue": {
        "vid": 50397282435265
      },
      "3xl|splash proof|yellow": {
        "vid": 50397282468033
      },
      "3xl|splash proof|pink": {
        "vid": 50397282500801
      },
      "3xl|silk satin|white": {
        "vid": 50397282533569,
        "price": 1033.0
      },
      "3xl|silk satin|black": {
        "vid": 50397282566337,
        "price": 1033.0
      },
      "3xl|silk satin|cream": {
        "vid": 50397282599105,
        "price": 1033.0
      },
      "3xl|silk satin|red": {
        "vid": 50397282631873,
        "price": 1033.0
      },
      "3xl|silk satin|green": {
        "vid": 50397282664641,
        "price": 1033.0
      },
      "3xl|silk satin|blue": {
        "vid": 50397282697409,
        "price": 1033.0
      },
      "3xl|silk satin|yellow": {
        "vid": 50397282730177,
        "price": 1033.0
      },
      "3xl|silk satin|pink": {
        "vid": 50397282762945,
        "price": 1033.0
      },
      "4xl|splash proof|white": {
        "vid": 50397282795713
      },
      "4xl|splash proof|black": {
        "vid": 50397282828481
      },
      "4xl|splash proof|cream": {
        "vid": 50397282861249
      },
      "4xl|splash proof|red": {
        "vid": 50397282894017
      },
      "4xl|splash proof|green": {
        "vid": 50397282926785
      },
      "4xl|splash proof|blue": {
        "vid": 50397282959553
      },
      "4xl|splash proof|yellow": {
        "vid": 50397282992321
      },
      "4xl|splash proof|pink": {
        "vid": 50397283025089
      },
      "4xl|silk satin|white": {
        "vid": 50397283057857,
        "price": 1033.0
      },
      "4xl|silk satin|black": {
        "vid": 50397283090625,
        "price": 1033.0
      },
      "4xl|silk satin|cream": {
        "vid": 50397283123393,
        "price": 1033.0
      },
      "4xl|silk satin|red": {
        "vid": 50397283156161,
        "price": 1033.0
      },
      "4xl|silk satin|green": {
        "vid": 50397283188929,
        "price": 1033.0
      },
      "4xl|silk satin|blue": {
        "vid": 50397283221697,
        "price": 1033.0
      },
      "4xl|silk satin|yellow": {
        "vid": 50397283254465,
        "price": 1033.0
      },
      "4xl|silk satin|pink": {
        "vid": 50397283287233,
        "price": 1033.0
      }
    },
    "desc": "issued.\n\npuffer vest, black. the only black-base piece in the pack. handmade to order.\n\nfront, white ink, beside the zip pull: commission for uniform provision · standard issue — tier 2 · cycle 04.\nback, below the collar: barcode. unit no. 04-2891.\n\nblack issue exists. the reason is not disclosed at this tier.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-jacket",
    "name": "the jacket",
    "observed": "read before spoken to",
    "sub": "case — 002 · the standard pack",
    "type": "puffer jacket",
    "price": 343.0,
    "handle": "mens-puffer-jacket",
    "categories": [
      "men",
      "women"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039061_0_3d.jpg?v=1783805591",
    "options": [
      {
        "label": "select size",
        "values": [
          "xs",
          "s",
          "m",
          "l",
          "xl",
          "2xl"
        ]
      },
      {
        "label": "select fabric",
        "values": [
          "splash proof",
          "silk satin"
        ]
      }
    ],
    "variants": {
      "xs|splash proof": {
        "vid": 50397274505409
      },
      "xs|silk satin": {
        "vid": 50397274538177,
        "price": 633.0
      },
      "s|splash proof": {
        "vid": 50397274570945
      },
      "s|silk satin": {
        "vid": 50397274603713,
        "price": 633.0
      },
      "m|splash proof": {
        "vid": 50397274636481
      },
      "m|silk satin": {
        "vid": 50397274669249,
        "price": 633.0
      },
      "l|splash proof": {
        "vid": 50397274702017
      },
      "l|silk satin": {
        "vid": 50397274734785,
        "price": 633.0
      },
      "xl|splash proof": {
        "vid": 50397274767553
      },
      "xl|silk satin": {
        "vid": 50397274800321,
        "price": 633.0
      },
      "2xl|splash proof": {
        "vid": 50397274833089
      },
      "2xl|silk satin": {
        "vid": 50397274865857,
        "price": 633.0
      }
    },
    "desc": "issued.\n\npuffer jacket, white. handmade to order. the pack's outerwear piece, and the one that inverts the layout.\n\nfront, oversized, split across the center zipper seam: barcode. unit no. 04-2891.\nback, upper panel: commission for uniform provision · standard issue — tier 2 · cycle 04.\n\na unit wearing this one is barcode-forward. read before spoken to.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-beanie",
    "name": "the beanie",
    "observed": "a warm standard",
    "sub": "case — 002 · the standard pack",
    "type": "knit cap",
    "price": 63.0,
    "handle": "beanie",
    "categories": [
      "men",
      "women",
      "accessories"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039496_0_3d.jpg?v=1783806252",
    "options": [
      {
        "label": "select size",
        "values": [
          "xs",
          "s/m",
          "l/xl",
          "xxl"
        ]
      }
    ],
    "variants": {
      "xs": {
        "vid": 50397272277185
      },
      "s/m": {
        "vid": 50397272309953
      },
      "l/xl": {
        "vid": 50397272342721
      },
      "xxl": {
        "vid": 50397272375489
      }
    },
    "desc": "issued.\n\nknit cap. recycled poly jersey, double layered. handmade to order.\n\ncuff stamp, wraparound: commission for uniform provision · standard issue — tier 2 · cycle 04.\nunit no. 04-2891.\n\nheads are standardized for a reason. warmth is an allotment like anything else.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  },
  {
    "id": "the-ration",
    "name": "the ration",
    "observed": "a unit of measure",
    "sub": "case — 002 · the standard pack",
    "type": "thermal bottle",
    "price": 53.0,
    "handle": "stainless-steel-thermal-bottle",
    "categories": [
      "accessories"
    ],
    "img": "https://cdn.shopify.com/s/files/1/0865/2721/3761/files/3039059_0_3d.jpg?v=1783805472",
    "options": [
      {
        "label": "select finish",
        "values": [
          "silver",
          "white"
        ]
      }
    ],
    "variants": {
      "silver": {
        "vid": 50397274439873
      },
      "white": {
        "vid": 50397274472641
      }
    },
    "desc": "issued.\n\nthermal bottle, stainless steel. 7oz. screw top. bpa free. handmade to order.\n\nstamp: commission for uniform provision · standard issue — tier 2 · cycle 04.\nunit no. 04-2891.\n\na cup is a unit of measure. the commission does not just measure what you drink.\n\nvrsn · rebel in luxury · est. 3:33\ncase — 002 · the standard pack",
    "alt": "the object in question."
  }
];

window.VRSN_IMG = function (url, w) {
  return url + '&width=' + (w || 900);
};

window.VRSN_VARIANT = function (p, sel) {
  if (!p.variants) return null;
  return p.variants[sel.join('|')] || null;
};
